In [1]:
import numpy as np

### This is my notebook following the instructions from:
https://web.stanford.edu/class/cs231a/section/section1.pdf

In [7]:
v = np.array([[1],
             [2],
             [3]])

In [8]:
v.shape

(3, 1)

In [9]:
v + v

array([[2],
       [4],
       [6]])

In [10]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
v3 = np.array([7, 8, 9])
M = np.vstack([v1, v2, v3])
print (M)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
# Dot multiplication
print(M.dot(v))

[[14]
 [32]
 [50]]


In [13]:
# Transposing the Dot Product
print (v.T.dot(v))

[[14]]


In [14]:
# Elementwise Multiplication
np.multiply(M,v)

array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27]])

In [15]:
# Transposing
print (M.T)
print (M.T.shape, v.T.shape)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
(3, 3) (1, 3)


In [16]:
# Taking a Determinant and it's inverse
i_m = np.array([[3,0,2], [2,0,-2],[0,1,1]])
print (np.linalg.inv(i_m))

[[ 0.2  0.2  0. ]
 [-0.2  0.3  1. ]
 [ 0.2 -0.3 -0. ]]


In [17]:
# If determinant is = 0 matrix is not invertible
print (np.linalg.det(i_m))

10.000000000000002


In [18]:
# Eignvalues and Eignvectors
eigvals, eigvecs = np.linalg.eig(M)
print (eigvals)

[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]


In [20]:
U, S, Vtranspose = np.linalg.svd(i_m)

In [21]:
U

array([[-0.95123459,  0.23048583, -0.20500982],
       [-0.28736244, -0.90373717,  0.31730421],
       [-0.11214087,  0.36074286,  0.92589903]])

In [22]:
S

array([3.72021075, 2.87893436, 0.93368567])

In [23]:
Vtranspose

array([[-0.9215684 , -0.03014369, -0.38704398],
       [-0.38764928,  0.1253043 ,  0.91325071],
       [ 0.02096953,  0.99166032, -0.12716166]])